### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework2G2#32]
Hi @WildJimmy,
I just wanna know how much have you worked on your documentation part. We are supposed to compare the execution time using Einstein notation for different platforms, Aren't we?

**Comment by WildJimmy** [comment]
Hello,

Yep, I was mainly waiting for the algorithm to be done since I think it's probably easier to document the code once it's finished, but then yesterday was crazy (I probably should have communicated that). I'll have the documentation done sometime today/tonight so there'll be at least a little time for review.
